#!/usr/bin/env bash

if
  [[ -s "/home/deltasoft/.rvm/gems/ruby-1.9.3-p551@global/environment" ]]
then
  source "/home/deltasoft/.rvm/gems/ruby-1.9.3-p551@global/environment"
  exec ruby "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/deltasoft/.rvm/gems/ruby-1.9.3-p551@global/environment'" >&2
  exit 1
fi
