#!/usr/bin/env bash

if
  [[ -s "/home/deltasoft/.rvm/gems/ruby-1.9.3-p551/environment" ]]
then
  source "/home/deltasoft/.rvm/gems/ruby-1.9.3-p551/environment"
  exec bundle "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/deltasoft/.rvm/gems/ruby-1.9.3-p551/environment'" >&2
  exit 1
fi
